### ISSUE TITLE
[TODO] CSS Selectors

### ISSUE THREAD

**Issue by Ereasai** [Ereasai/fa22-cse110-lab3#3]
# Overview
CSS Selectors
# Description
CSS selectors allow you to select the HTML element you want to style. Each type of selector targets a different identifier on your HTML element. 

- [x] Class Selector
- [x] ID Selector
- [x] Universal Selector
- [x] Element Selector
- [x] Attribute Selector
- [x] Pseudo-class Selector
- [x] Selector List
- [x] Combinators (must use one of each)
  - [x] Descendant Combinator
  - [x] Child Combinator
  - [x] General Sibling Combinator
  - [x] Adjacent Sibling Combinator
  - [x] Combining Two Selectors
# References
https://canvas.ucsd.edu/courses/39754/assignments/526073
